/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package msgies;

public class App {
	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());

		JavaProducer prod = new JavaProducer();
		prod.run();

		JavaConsumer cons = new JavaConsumer();
		cons.run();
	}
}
